[profile.default]
solc_version = "0.8.17"
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["*"]

[rpc_endpoints]
localhost = "http://127.0.0.1:8545"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
